[package]
name = "terra-tui"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
thiserror = "1.0.37"

terra-core = { path = "../terra-core" }

serde = "1.0.148"
serde_json = "1.0.89"
