name: Rust

on:
  push:
    branches: ['master']
    paths:
      - 'data/resources/**'
      - '.github/workflows/**'
      - 'terra-*/**/*.rs'
      - '**/Cargo.*'
      - '!terra-res/'
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    name: Check changes
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.get_changes.outputs.files }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: get_changes
        with:
          filters: |
            files:
              - '.github/workflows/**'
              - 'data/resources/**'
              - 'terra-*/**'
              - '**/Cargo.*'
              - '!terra-res/'

  build:
    strategy:
      matrix:
        platform:
          - name: linux
            os: ubuntu-latest
            ext: ''
          - name: windows
            os: windows-latest
            ext: .exe

    needs: check_changes
    if: ${{ needs.check_changes.outputs.changed == 'true' }}
    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential pkg-config libgtk-3-dev unzip
        if: matrix.platform.os != 'windows-latest'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Build
        run: cargo build --release
        env:
          UPDATE_PLATFORM: ${{ matrix.platform.name }}

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Extract resources
        # run: 7z x -otarget/release/resources ./data/resources.zip
        run: mv data/resources target/release/resources

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: |
            target/release/terra-rs${{ matrix.platform.ext }}
            target/release/resources/
